*> ISSUECARD <customer-id> <account> <card-number> <type> <cvv>
*>     <expiry> <tx-limit>
*> Issues a card linked to an account owned by the customer. The card
*> number, CVV and expiry (YYMM) are generated by the caller -- COBOL
*> only enforces uniqueness of the card number and owns every decision
*> about the card from here on (see card-record.cpy). <type> must be
*> DEBIT or CREDIT (CREDIT is accepted but behaves identically to DEBIT
*> in this phase -- no separate credit-line product yet). <tx-limit> is
*> the maximum amount a single CARDPAYMENT may charge.
IDENTIFICATION DIVISION.
PROGRAM-ID. OP-ISSUECARD.

DATA DIVISION.
WORKING-STORAGE SECTION.
COPY "account-record.cpy"
    REPLACING ==ACCOUNT-RECORD==    BY ==WS-ACCOUNT-RECORD==
              ==FD-ACCOUNT-NUMBER== BY ==WS-ACCOUNT-NUMBER==
              ==FD-OWNER-NAME==     BY ==WS-OWNER-NAME==
              ==FD-BALANCE==        BY ==WS-BALANCE==
              ==FD-CUSTOMER-ID==    BY ==WS-ACCOUNT-CUSTOMER-ID==
              ==FD-ACCOUNT-TYPE==   BY ==WS-ACCOUNT-TYPE==
              ==FD-ACCOUNT-STATUS== BY ==WS-ACCOUNT-STATUS==.
COPY "card-record.cpy"
    REPLACING ==CARD-RECORD==       BY ==WS-CARD-RECORD==
              ==CD-CARD-NUMBER==    BY ==WS-CARD-NUMBER==
              ==CD-ACCOUNT-NUMBER== BY ==WS-CARD-ACCOUNT==
              ==CD-CUSTOMER-ID==    BY ==WS-CARD-CUSTOMER-ID==
              ==CD-CARD-TYPE==      BY ==WS-CARD-TYPE==
              ==CD-CVV==            BY ==WS-CVV==
              ==CD-EXPIRY==         BY ==WS-EXPIRY==
              ==CD-STATUS==         BY ==WS-CARD-STATUS==
              ==CD-TX-LIMIT==       BY ==WS-TX-LIMIT==.
01  WS-ARG-INDEX          PIC 9(2).
01  WS-ARG-CUSTOMER       PIC X(10).
01  WS-ARG-ACCOUNT        PIC X(10).
01  WS-ARG-CARD           PIC X(20).
01  WS-ARG-TYPE           PIC X(10).
01  WS-ARG-CVV            PIC X(10).
01  WS-ARG-EXPIRY         PIC X(10).
01  WS-ARG-LIMIT          PIC X(80).
01  WS-CUSTOMER-ID        PIC 9(6).
01  WS-TYPE-VALID         PIC X VALUE "N".
01  WS-ACCT-REPO-FUNCTION PIC X(10).
01  WS-ACCT-REPO-FOUND    PIC X.
01  WS-ACCT-REPO-EOF      PIC X.
01  WS-CARD-REPO-FUNCTION PIC X(10).
01  WS-CARD-REPO-FOUND    PIC X.
01  WS-CARD-REPO-EOF      PIC X.

LINKAGE SECTION.
01  LK-ARGC  PIC 9(2).

PROCEDURE DIVISION USING BY REFERENCE LK-ARGC.
MAIN-OP-ISSUECARD.
    IF LK-ARGC < 8
        DISPLAY "ERR|Insufficient arguments"
    ELSE
        MOVE 2 TO WS-ARG-INDEX
        DISPLAY WS-ARG-INDEX UPON ARGUMENT-NUMBER
        ACCEPT WS-ARG-CUSTOMER FROM ARGUMENT-VALUE
        MOVE 3 TO WS-ARG-INDEX
        DISPLAY WS-ARG-INDEX UPON ARGUMENT-NUMBER
        ACCEPT WS-ARG-ACCOUNT FROM ARGUMENT-VALUE
        MOVE 4 TO WS-ARG-INDEX
        DISPLAY WS-ARG-INDEX UPON ARGUMENT-NUMBER
        ACCEPT WS-ARG-CARD FROM ARGUMENT-VALUE
        MOVE 5 TO WS-ARG-INDEX
        DISPLAY WS-ARG-INDEX UPON ARGUMENT-NUMBER
        ACCEPT WS-ARG-TYPE FROM ARGUMENT-VALUE
        MOVE 6 TO WS-ARG-INDEX
        DISPLAY WS-ARG-INDEX UPON ARGUMENT-NUMBER
        ACCEPT WS-ARG-CVV FROM ARGUMENT-VALUE
        MOVE 7 TO WS-ARG-INDEX
        DISPLAY WS-ARG-INDEX UPON ARGUMENT-NUMBER
        ACCEPT WS-ARG-EXPIRY FROM ARGUMENT-VALUE
        MOVE 8 TO WS-ARG-INDEX
        DISPLAY WS-ARG-INDEX UPON ARGUMENT-NUMBER
        ACCEPT WS-ARG-LIMIT FROM ARGUMENT-VALUE

        EVALUATE FUNCTION UPPER-CASE(WS-ARG-TYPE)
            WHEN "DEBIT"
            WHEN "CREDIT"
                MOVE "Y" TO WS-TYPE-VALID
            WHEN OTHER
                MOVE "N" TO WS-TYPE-VALID
        END-EVALUATE

        IF WS-TYPE-VALID = "N"
            DISPLAY "ERR|Invalid card type"
        ELSE
            MOVE FUNCTION NUMVAL(WS-ARG-CUSTOMER) TO WS-CUSTOMER-ID
            MOVE FUNCTION NUMVAL(WS-ARG-ACCOUNT) TO WS-ACCOUNT-NUMBER

            MOVE "READ" TO WS-ACCT-REPO-FUNCTION
            CALL "ACCOUNT-REPOSITORY" USING BY REFERENCE WS-ACCT-REPO-FUNCTION
                WS-ACCOUNT-RECORD WS-ACCT-REPO-FOUND WS-ACCT-REPO-EOF

            IF WS-ACCT-REPO-FOUND = "N"
                DISPLAY "ERR|Account not found"
            ELSE
                IF WS-ACCOUNT-CUSTOMER-ID NOT = WS-CUSTOMER-ID
                    DISPLAY "ERR|This account does not belong to the customer"
                ELSE
                    MOVE FUNCTION NUMVAL(WS-ARG-CARD) TO WS-CARD-NUMBER

                    MOVE "READ" TO WS-CARD-REPO-FUNCTION
                    CALL "CARD-REPOSITORY" USING BY REFERENCE WS-CARD-REPO-FUNCTION
                        WS-CARD-RECORD WS-CARD-REPO-FOUND WS-CARD-REPO-EOF

                    IF WS-CARD-REPO-FOUND = "Y"
                        DISPLAY "ERR|A card with that number already exists"
                    ELSE
                        MOVE WS-ACCOUNT-NUMBER TO WS-CARD-ACCOUNT
                        MOVE WS-CUSTOMER-ID TO WS-CARD-CUSTOMER-ID
                        MOVE FUNCTION UPPER-CASE(WS-ARG-TYPE) TO WS-CARD-TYPE
                        MOVE FUNCTION NUMVAL(WS-ARG-CVV) TO WS-CVV
                        MOVE FUNCTION NUMVAL(WS-ARG-EXPIRY) TO WS-EXPIRY
                        MOVE FUNCTION NUMVAL(WS-ARG-LIMIT) TO WS-TX-LIMIT
                        MOVE "ACTIVE" TO WS-CARD-STATUS

                        MOVE "WRITE" TO WS-CARD-REPO-FUNCTION
                        CALL "CARD-REPOSITORY" USING BY REFERENCE WS-CARD-REPO-FUNCTION
                            WS-CARD-RECORD WS-CARD-REPO-FOUND WS-CARD-REPO-EOF

                        IF WS-CARD-REPO-FOUND = "Y"
                            DISPLAY "OK|Card issued"
                        ELSE
                            DISPLAY "ERR|The card could not be created"
                        END-IF
                    END-IF
                END-IF
            END-IF
        END-IF
    END-IF
    GOBACK.

END PROGRAM OP-ISSUECARD.
