      *> Shared layout for CARD-FILE (cards.dat). Included as-is (prefix
      *> CD-) in the FD SECTION of card_repository.cbl, and via
      *> REPLACING under a different prefix everywhere else.
      *>
      *> The card number, CVV and expiry are generated by the caller at
      *> issue time (same division of labor as account numbers -- see
      *> generate_account() in client/app/mainframe/client.py): COBOL
      *> owns uniqueness and every decision about the card from then on,
      *> but does not mint the PAN itself.
      *>
      *> CD-CARD-TYPE reserves the value CREDIT for a future, separate
      *> credit-line product; today DEBIT and CREDIT behave identically.
      *> CD-TX-LIMIT caps a single CARDPAYMENT, not a rolling daily or
      *> monthly total (that needs date-bucketed ledger queries).
       01  CARD-RECORD.
           05 CD-CARD-NUMBER       PIC 9(16).
           05 CD-ACCOUNT-NUMBER    PIC 9(6).
           *> Denormalized owner, redundant with the linked account's
           *> FD-CUSTOMER-ID -- kept here so OP-CARDS can list a
           *> customer's cards via an alternate key without first
           *> reading every card's account.
           05 CD-CUSTOMER-ID       PIC 9(6).
           05 CD-CARD-TYPE         PIC X(10).
           05 CD-CVV               PIC 9(3).
           *> YYMM, numerically sortable (e.g. 2812 = December 2028).
           05 CD-EXPIRY            PIC 9(4).
           05 CD-STATUS            PIC X(8).
           05 CD-TX-LIMIT          PIC 9(12) COMP-3.
